#!/bin/bash

init()
{
    # add fwmark
    /usr/sbin/ip rule add fwmark 0x56/0x56 table 100
    /usr/sbin/ip route add local 0.0.0.0/0 dev lo table 100

    ########### tcp ###########
    # create new chain
    /usr/sbin/iptables -t nat -N GEDIRECT
    # ignore remote server
    /usr/sbin/iptables -t nat -A GEDIRECT -d $1 -j RETURN
    # ignore lan ip
    /usr/sbin/iptables -t nat -A GEDIRECT -d 0.0.0.0/8 -j RETURN
    /usr/sbin/iptables -t nat -A GEDIRECT -d 10.0.0.0/8 -j RETURN
    /usr/sbin/iptables -t nat -A GEDIRECT -d 127.0.0.0/8 -j RETURN
    /usr/sbin/iptables -t nat -A GEDIRECT -d 169.254.0.0/16 -j RETURN
    /usr/sbin/iptables -t nat -A GEDIRECT -d 172.16.0.0/12 -j RETURN
    /usr/sbin/iptables -t nat -A GEDIRECT -d 192.168.0.0/16 -j RETURN
    /usr/sbin/iptables -t nat -A GEDIRECT -d 224.0.0.0/4 -j RETURN
    /usr/sbin/iptables -t nat -A GEDIRECT -d 240.0.0.0/4 -j RETURN
    # forwarding
    /usr/sbin/iptables -t nat -A GEDIRECT -p tcp -j REDIRECT --to-ports $2

    ########### udp ###########
    # create new chain
    /usr/sbin/iptables -t mangle -N GEDIRECT
    # ignore lan ip
    /usr/sbin/iptables -t mangle -A GEDIRECT -d 0.0.0.0/8 -j RETURN
    /usr/sbin/iptables -t mangle -A GEDIRECT -d 10.0.0.0/8 -j RETURN
    /usr/sbin/iptables -t mangle -A GEDIRECT -d 127.0.0.0/8 -j RETURN
    /usr/sbin/iptables -t mangle -A GEDIRECT -d 169.254.0.0/16 -j RETURN
    /usr/sbin/iptables -t mangle -A GEDIRECT -d 172.16.0.0/12 -j RETURN
    /usr/sbin/iptables -t mangle -A GEDIRECT -d 192.168.0.0/16 -j RETURN
    /usr/sbin/iptables -t mangle -A GEDIRECT -d 224.0.0.0/4 -j RETURN
    /usr/sbin/iptables -t mangle -A GEDIRECT -d 240.0.0.0/4 -j RETURN
    # forwarding
    /usr/sbin/iptables -t mangle -A GEDIRECT -p udp -j TPROXY --on-port $2 --tproxy-mark 0x56/0x56
}


enable()
{
    /usr/sbin/iptables -t nat -A PREROUTING -s $1 -p tcp -j GEDIRECT
    /usr/sbin/iptables -t mangle -A PREROUTING -s $1 -p udp -j GEDIRECT
}

disable()
{
    /usr/sbin/iptables -t nat -D PREROUTING -s $1 -p tcp -j GEDIRECT 2>/dev/null
    /usr/sbin/iptables -t mangle -D PREROUTING -s $1 -p udp -j GEDIRECT 2>/dev/null
}

clear()
{
    # remove iptables rules
    /usr/sbin/iptables -t nat -F GEDIRECT
    /usr/sbin/iptables -t nat -X GEDIRECT 2>/dev/null
    /usr/sbin/iptables -t mangle -F GEDIRECT
    /usr/sbin/iptables -t mangle -X GEDIRECT 2>/dev/null
    # remove fmark
    /usr/sbin/ip rule del fwmark 0x56/0x56 table 100 2>/dev/null
    /usr/sbin/ip route del local 0.0.0.0/0 dev lo table 100 2>/dev/null
}

# usage
USAGE="\
Usage: $(basename $0) COMMAND [ARGS...]

Available commands:
    init SERVER LOCAL_PORT      Init the iptables rules.
    clear                       Clear the iptables rules.
    enable LOCAL_IP             Enable client routing.
    disable LOCAL_IP            Disable client routing.\
"

case $1 in
    init)
        if [ "$2" = "" ] || [ "$3" = "" ]; then
            echo "$USAGE"
        else
            clear
            init $2 $3
        fi
        ;;

    enable)
        if [ "$2" = "" ]; then
            echo "$USAGE"
        else
            disable $2
            enable $2
        fi
        ;;

    disable)
        if [ "$2" = "" ]; then
            echo "$USAGE"
        else
            disable $2
        fi
        ;;

    clear)
        clear
        ;;

    *)
        echo "$USAGE"
        ;;
esac
